/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export enum DrinkType {
    Beer = "beer",
    Wine = "wine",
    Cocktail = "cocktail",
    Mocktail = "mocktail",
    Soft = "soft",
    Spirit = "spirit",
    Other = "other",
}

export class Drink extends SpeakeasyBase {
    /**
     * The name of the drink
     */
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name: string;

    /**
     * The price of one unit of the drink in US cents.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "price" })
    price: number;

    /**
     * The product code of the drink, only available when authenticated.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "productCode" })
    productCode?: string;

    /**
     * The number of units of the drink in stock, only available when authenticated.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "stock" })
    stock?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "type" })
    type: DrinkType;
}
